## IIBM Bootcamp 2022: Day 3 Morning

### Instructors Carlos Valle (cgvalle@uc.cl) and Gabriela Vargas (givargas@uc.cl)

This jupyter noteboook will cover the use of the libraries NumPy and Matplotlib.

### Day Agenda:

***Morning***
1. Working with NumPy
    * Arrays
    * Vector operations
    * Matrix operations
    * point-wise operations
2. Working with Matplotlib
    * Anatomy of a figure
    * Fundamental principles of ploting library
    * Design of a figure
    * Types of figures
    
***Afternoon***
3. Group Project
    * Working with real-world data

4. Don't forget to send your work!



# 1. Working with NumPy

NumPy is a Python library used for working with arrays (Matrixs and Vectors) that contain numerical data (`float`, `int`). Is one of the most (if not the most) package for working in scientific computing in Python. It provides multidimensional array definitions, and several handie functions that are common while working with arrays.

Since NumPy is an external package to Python, it needs to be installed. Fortunately, Google Colab provides it by default. If it is not installed, you can installed running `pip install numpy` in your computer terminal.

Let's see how to use it!. First it needs to be imported with the line `import numpy`. However, it is common for this library to be loaded as `import numpy as np`, where now you can use it by only typing `np`.

In [1]:
import numpy as np  # NumPy is not imported and ready to be use

As mentioned before, NumPy is the defecto library for working with ararys. Let's create one:

In [2]:
# Out first numpy array
example_array = np.array([1, 2, 3, 4])

The variable `first_array` has a vector with the elements `[1, 2, 3, 4]`. If we check the type, it corresponds to a `numpy.ndarray`. `ndarray` is the type of the variable (like `int`, `float`, `list`, `dict`, etc.)

In [3]:
type(example_array)

numpy.ndarray

## Wait, is the input of `np.array` a list ? yes

If we need a list to create and array, why don't we just use a list ?. The answer is that Python implementation of lists is not really fast. Let's test it by comparing the time of summing two arrays

In [4]:
vector_size = 100000

# Creating vectors
list_vector_A = list(range(vector_size))  # List
list_vector_B = list(range(10, vector_size + 10))  # List


In [5]:
def python_sum(vector_a, vector_b):
    final_vector = []
    N = len(vector_a)
    for i in range(N):
        final_vector.append(vector_a[i] + vector_b[i])

%time python_sum(list_vector_A, list_vector_B)

CPU times: user 15.1 ms, sys: 3.71 ms, total: 18.8 ms
Wall time: 18.4 ms


In [6]:
def numpy_sum(vector_a, vector_b):
    final_vector = vector_a + vector_b

%time numpy_sum(list_vector_A, list_vector_B)    

CPU times: user 1.58 ms, sys: 731 µs, total: 2.31 ms
Wall time: 2.45 ms


Not only the NumPy way was **faster**, but also a **lot simpler**.

## Arrays: `ndarray` objects have a lot of useful information and methods

Some usefull methods are:
### [`ndarray.shape` ](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html) returns dimension of the array

In [7]:
# A list only has one dimension!
array = np.array([1, 2, 3, 4])
array.shape

(4,)

In [8]:
# A list inside a list has two dimension!
array = np.array([[1, 2, 3, 4]])
array.shape

(1, 4)

In [9]:
# A list inside a list inside a list has three dimensions!
array = np.array([[[1, 2, 3, 4]]])
array.shape

(1, 1, 4)

### [`ndarray.dtype` ](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.dtype.html) returns the type of number inside

In [10]:
# Since all numbers inside are int, the type is also a int
array = np.array([[1, 2, 3, 4]])
array.dtype

dtype('int64')

In [11]:
# Since all numbers inside are float, the type is also a float
array = np.array([[1.0, 2.0, 3.0, 4.0]])
array.dtype

dtype('float64')

In [12]:
# Since one of the numbers inside is a float, the type is also a float
array = np.array([[1.0, 2, 3, 4]])
array.dtype

dtype('float64')

### [`ndarray.T` ](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html)  return a transpose array

In [13]:
array = np.array([[1.0, 2, 3, 4]])
print("Original Array dimension:", array.shape)

array_transpose = array.T
print("Original Array dimension:", array_transpose.shape)

Original Array dimension: (1, 4)
Original Array dimension: (4, 1)


## Arrays can have lots of dimension

In [14]:
multi_dim_array = np.random.rand(4, 3, 2, 5)
#print(multi_dim_array)
print(multi_dim_array.shape)

(4, 3, 2, 5)


## Array Multiplication

![multiplication](https://raw.githubusercontent.com/CarlosValleA/IIBM-BootCamp/main/images/D2_matrix_mul.png)

## Vector normal multiplication

In [52]:
# Normal multiplication
array_1 = np.array([[1, 2, 3, 4]])
array_2 = np.array([[1, 2, 3, 4]]).T
np.matmul(array_1, array_2)

array([[30]])

## Vector dot multiplication

In [53]:
array_1 = np.array([[1, 2, 3, 4]])
array_2 = np.array([[1, 2, 3, 4]])
array_1 * array_2 # Dot product

array([[ 1,  4,  9, 16]])

## Matrix normal multiplication

In [58]:
matrix_1 = np.array([[1, 0], [0, 1]])
matrix_2 = np.array([[4, 1], [2, 2]])
np.matmul(matrix_1, matrix_2)

array([[4, 1],
       [2, 2]])

## Matrix dot multiplication

In [70]:
matrix_1 = np.array([[1, 0], [0, 1]])
matrix_2 = np.array([[4, 1], [2, 2]])
matrix_1 * matrix_2

array([[4, 0],
       [0, 2]])

Mores methods `ndarray` can be found [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

# 3.1 Exercise 

Create a numpy a array with the shape
$$
array = 
\left [ \begin{array}{c} 
0.8 & 1.2\\
-0.4 & -0.1\\
-0.6 & -0.9
\end{array}\right ]
$$ 

In [71]:
array = "<TODO>"

# 3.2 Exercise 

Sum all the elements of the previous array

In [ ]:
array_sum = "<TODO>"

# 3.3 Exercise 

Multiply the array by itself. **HINT: you may need to transpose!**

In [ ]:
array_multi = "<TODO>"

# 3.4 Exercise 

Point-wise multiplication of created array.

In [ ]:
array_point = "<TODO>"

# 4. Don't forget to send your work!

Please don't forget to send your work to give you feedback about your progress to this [form](https://forms.gle/VjepgcVYe9ZYab269). To send it, you need to download the Notebook from Colab's webpage and upload it in the last question of the form.
